# Generated by Django 5.0.6 on 2024-07-22 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
